server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  application:
    name: Global Solution
logging:
  level:
    org.springframework.security: debug

configuration:
  bearer:
    token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImtpZEtleSJ9.eyJkYXRhIjp7Im5hbWUiOiJHbG9iYWwgU29sdXRpb24iLCJ1c2VySWQiOjM1MjUwLCJhcHBsaWNhdGlvbk5hbWUiOiJHbG9iYWwgU29sdXRpb24iLCJpZCI6MTU4NCwidHlwZSI6InVzZXItYXBwbGljYXRpb24ifSwiaWF0IjoxNzE3NDE4NzM0LCJleHAiOjIwMzI3Nzg3MzQsImF1ZCI6ImdmdyIsImlzcyI6ImdmdyJ9.J5CDavdTeNb0L3nhkbDUYWMvS5rSlfj7X1vnEoQhlR8L8U8tPMP4rzff1a_CchSLvFsox5_iCkhjM7uFGhce6412g3LtvHdvY_x3cc3BZAGoFLWKd1wGn6A5RxciMPkmH2qqThvfS6Rn9G0akwCpNv0Fn4UtNezc0888szaetaSkjQlWGuDH9too1ZhovdosylxKTAQTe_o95mCEBxdezjRqC6-HOMHF3p7MZ4y6vt4A7d5lmkc9Qtm9UkBVa0VHPyWrfVtcRJxndu2lidxIdPswTGIP2HzFQeYxvWNXXZ5Qg2kXflt-fupQblKdx4hZjDaJGVoKLsym8ujYkHYZ4a3kHIHHMjWKFCxeS8CF_0QvHbEpHvAkIb82a-uMq_IsQlz2pzn0Wx6hhDGoINkEFaQ67VZeayI7klnWb9EQ5AABHJZTd9Br3N3AbDaVBlQzDHmYA3Xj3716rCmQwkBDPGi3t_OuPmdMbE08g6WVwMbIHitPo5saQDZBeq4IJbJp
